app_prototypes:
  twitter_clone:
  prompt_app_name: twitter clone app
  prompt_app_idea: a roda twitter clone application that lets you post short messages, repost them (retweet)
  prompt_app:
    "name: twitter
    controller:
      - GET /feed - list all tweets in creation order - if you are logged in list per user
      - GET /user - display user infos such as image url, nickname and bio
      - GET /user/feed - list all tweets of the user
      - GET /tweets/id - get the single tweet by id and return the tweet info and user information in the response
      - POST /tweet - save tweet text to redis and user id
      - POST /tweets/id - save tweet text to redis and user id
     model:
       - Tweet.all - get all the tweets
       - Tweet.feed username: - get all the tweets (using Tweet.all) from the users you are following
       - Tweet.user username: - get all the tweets from a particular user
       - Tweet.get tweet_id: - get a single tweet using Sequel .where
       - Tweet.tweet text:, user: - tweets a particular text using the Twitter api, perform lenght check or otherwise raise TweetTooLongError, returns operation success
     model:
       - Tweet - fields: text, created_at, retweets_number
       - User - fields: username, hashed_password, bio
     environment:
       - require and setup the twitter gem
       - setup sqlite
       - test sqlite connection with select 1
       - create table tweet and users if the tabled are not yet created
    "
  weather_app:
